name: Build & Test

on:
  push:
    branches:
      - '*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Restore NuGet packages
      run: dotnet restore

    - name: Set user secret
      env:
        SECRET_VALUE: ${{ secrets.SteamApiKey }}
      run: |
        dotnet user-secrets set "SteamApiKey" "$SECRET_VALUE" --project "UserInfoAPITests/UserInfoAPITests.csproj"

    - name: Build project
      run: dotnet build --configuration Release

    - name: Run tests
      run: dotnet test UserInfoAPITests/UserInfoAPITests.csproj --configuration Release --logger "trx;LogFileName=test_results.trx" --results-directory TestResults

    - name: Publish test results
      uses: actions/upload-artifact@v2
      with:
        name: Test Results
        path: TestResults
